### PR TITLE
user journey map with drawio

### PR DESCRIPTION
**Pull request by oraNod**
To go with https://hackmd.io/udqRBwPoRC-N-wLOm01UEQ

We can put a draw.io file here to hack on a mind map with the Ansible community.

### CODE REVIEW

**Comment by samccann** [comment]
So how would I use the drawio file itself? I'm guessing after this initial commit, I could point the tool at that file to open it up and edit? Then I'd 'save' in a PR for review?

**Comment by samccann** [comment]
Ok I like that I can see a map and that we can each go in and edit it (assuming my above statement is correct). It's not really possible to comment on it tho. I wonder if we should take this 'big bubble' at a time and use the hackmd file to list out what we think are the top tasks per bubble.
So for example  - What are the top tasks for a novice? 

1. List out what we think they are, with community help, in the hackmd
2. Update the drawing when we agree on that bubble so to speak
3. Pick next important bubble, and use hackmd to brainstorm tasks for that persona at that user experience level
4. repeat...repeat...

**Comment by samccann** [comment]
and of course right after I wrote that I thought - why not document the 'top tasks' right here in github instead of hackmd?

**Comment by oraNod** [comment]
@samccann Here you go: https://github.com/ansible-community/community-team/pull/149

I'll port the personas over as well maybe.

**Comment by oraNod** [comment]
@samccann I think the mindmap is just an extra thing that's good for brainstorming user journeys collaboratively. It also offers a nice visual representation that sort of resonates more immediately when you show it to others.

My thoughts were that people can hack on the drawio mindmap in this repo with the online editor or a desktop app. Then generate an SVG for easier sharing. People could even create new maps for individual personas or whatever journeys they feel like.

We can then translate the mindmap details to the MD file and capture them in a form that is easy to get a vote on etc. Does that make sense?

**Comment by GregSutcliffe** [comment]
I like the mindmap - having to download the file is irritating but if we stick with it then draw.io seems to have GitHub integration we could look at.

I'll add an item for next week to start adding some thoughts to this, in particular around community gardening, meetups, moderation, support, etc

**Comment by oraNod** [comment]
Thanks for the reviews folks. I'm going to close this one in favour of #151 I agree about the file download. I don't think that will work with the community. We should try and use native github as much as possible. This probably includes hackmd.

**Pull request closed without merging**
