### PR TITLE
User journey maps

### PR DESCRIPTION
**Pull request by oraNod**
This PR adds user journeys with mermaidJS to extend the Ansible docsite personas: https://hackmd.io/pZb5w5JFRQW3RJ73n23tlw?both#/

### CODE REVIEW

**Comment by samccann** [comment]
so how do I see the graphic this produces? So far I like it cuz it's text... and if it's text that produces a mindmap or some similar image, that seems the solution we're looking for :-)

**Comment by oraNod** [comment]
@samccann You can view the file natively in github. Unfortunately I don't think github supports mermaidJS mindmaps: https://mermaid.js.org/syntax/mindmap.html

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams

The mermaidJS journeys are a little awkward but at least they give us some sort of visual representation, keep everything in plain text, and avoid super long unordered lists.

**Comment by oraNod** [comment]
@samccann Maybe we should move this PR and the personas to the `ansible/docsite` repo? Community might be more inclined to look there.

**Comment by samccann** [comment]
@oraNod i'm really confused now. This used to be a PR that had the text (looked kinda yaml like?) for creating the mermaid mindmap.  Now it's just an MD file... What am I missing???

..that asside, yes it seems the docsite repo is probably a better place for this, you're right.

**Comment by oraNod** [comment]
Apologies for the noise here everyone but I do think this PR should move to the docsite repo. I'll shift things over to https://github.com/ansible/docsite/pull/138 and close this one for now. Thank you.

**Pull request closed without merging**
